name: Push dist

on:
  push: {}

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
      - name: yarn --frozen-lockfile
        run: yarn --frozen-lockfile
      - uses: kategengler/put-built-npm-package-contents-on-branch@v1.0.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}-dist
          token: ${{ secrets.GITHUB_TOKEN }}
